export const ERRORES_PERSONA = {
  PERSONA_NO_ENCONTRADA: 'PERSONA_NO_ENCONTRADA',
  PERSONA_DADA_DE_BAJA: 'PERSONA_DADA_DE_BAJA',
  DOCUMENTO_IDENTIDAD_DUPLICADO: 'DOCUMENTO_IDENTIDAD_DUPLICADO',
  DOCUMENTO_IDENTIDAD_INVALIDO: 'DOCUMENTO_IDENTIDAD_INVALIDO',
  CONTACTO_DUPLICADO: 'CONTACTO_DUPLICADO',
  MEMBRESIA_NO_ENCONTRADA: 'MEMBRESIA_NO_ENCONTRADA',
  PERSONA_Y_MEMBRESIA_DE_DISTINTA_INSTITUCION:
    'PERSONA_Y_MEMBRESIA_DE_DISTINTA_INSTITUCION',
  PERSONA_YA_VINCULADA: 'PERSONA_YA_VINCULADA',
} as const;
