export const REPOSITORIO_PERSONAS = Symbol('REPOSITORIO_PERSONAS');
export const REPOSITORIO_DOCUMENTOS_IDENTIDAD_PERSONA = Symbol(
  'REPOSITORIO_DOCUMENTOS_IDENTIDAD_PERSONA',
);
export const REPOSITORIO_MEDIOS_CONTACTO_PERSONA = Symbol(
  'REPOSITORIO_MEDIOS_CONTACTO_PERSONA',
);
export const REPOSITORIO_DIRECCIONES_PERSONA = Symbol(
  'REPOSITORIO_DIRECCIONES_PERSONA',
);
export const REPOSITORIO_VINCULOS_PERSONA_MEMBRESIA = Symbol(
  'REPOSITORIO_VINCULOS_PERSONA_MEMBRESIA',
);
