export const catalogos = {
  estadosConservacion: [
    { codigo: 'NUEVO', nombre: 'Nuevo', orden: 1 },
    { codigo: 'BUENO', nombre: 'Bueno', orden: 2 },
    { codigo: 'REGULAR', nombre: 'Regular', orden: 3 },
    { codigo: 'MALO', nombre: 'Malo', orden: 4 },
    { codigo: 'CRITICO', nombre: 'Crítico', orden: 5 },
    { codigo: 'NO_EVALUADO', nombre: 'No evaluado', orden: 6 },
  ],
  tiposComponenteInfraestructura: [
    { codigo: 'PUERTA', nombre: 'Puerta', categoria: 'ARQUITECTONICO' },
    { codigo: 'VENTANA', nombre: 'Ventana', categoria: 'ARQUITECTONICO' },
    { codigo: 'MURO', nombre: 'Muro', categoria: 'ESTRUCTURAL' },
    { codigo: 'COLUMNA', nombre: 'Columna', categoria: 'ESTRUCTURAL' },
    { codigo: 'TECHO', nombre: 'Techo', categoria: 'ARQUITECTONICO' },
    { codigo: 'PISO', nombre: 'Piso', categoria: 'ARQUITECTONICO' },
    { codigo: 'ESCALERA', nombre: 'Escalera', categoria: 'ARQUITECTONICO' },
    { codigo: 'RAMPA', nombre: 'Rampa', categoria: 'ACCESIBILIDAD' },
    { codigo: 'ASCENSOR', nombre: 'Ascensor', categoria: 'ACCESIBILIDAD' },
    { codigo: 'LUMINARIA', nombre: 'Luminaria', categoria: 'ELECTRICO' },
    {
      codigo: 'TOMACORRIENTE',
      nombre: 'Tomacorriente',
      categoria: 'ELECTRICO',
    },
    {
      codigo: 'TABLERO_ELECTRICO',
      nombre: 'Tablero eléctrico',
      categoria: 'ELECTRICO',
    },
    { codigo: 'LAVATORIO', nombre: 'Lavatorio', categoria: 'SANITARIO' },
    { codigo: 'INODORO', nombre: 'Inodoro', categoria: 'SANITARIO' },
    { codigo: 'CERCO', nombre: 'Cerco', categoria: 'SEGURIDAD' },
    { codigo: 'PORTON', nombre: 'Portón', categoria: 'SEGURIDAD' },
    { codigo: 'OTRO', nombre: 'Otro', categoria: 'OTRO' },
  ],
  unidadesMedida: [
    { codigo: 'UNIDAD', nombre: 'Unidad', simbolo: 'ud', magnitud: 'CANTIDAD' },
    { codigo: 'METRO', nombre: 'Metro', simbolo: 'm', magnitud: 'LONGITUD' },
    {
      codigo: 'METRO_CUADRADO',
      nombre: 'Metro cuadrado',
      simbolo: 'm²',
      magnitud: 'SUPERFICIE',
    },
    {
      codigo: 'METRO_CUBICO',
      nombre: 'Metro cúbico',
      simbolo: 'm³',
      magnitud: 'VOLUMEN',
    },
    { codigo: 'LITRO', nombre: 'Litro', simbolo: 'L', magnitud: 'VOLUMEN' },
    {
      codigo: 'KILOGRAMO',
      nombre: 'Kilogramo',
      simbolo: 'kg',
      magnitud: 'MASA',
    },
  ],
  tiposEspacioFisico: [
    { codigo: 'AULA', nombre: 'Aula', requiereAforo: true },
    { codigo: 'LABORATORIO', nombre: 'Laboratorio', requiereAforo: true },
    { codigo: 'BIBLIOTECA', nombre: 'Biblioteca', requiereAforo: true },
    { codigo: 'OFICINA', nombre: 'Oficina', requiereAforo: false },
    {
      codigo: 'SALA_REUNIONES',
      nombre: 'Sala de reuniones',
      requiereAforo: true,
    },
    {
      codigo: 'SERVICIOS_HIGIENICOS',
      nombre: 'Servicios higiénicos',
      requiereAforo: false,
    },
    { codigo: 'ALMACEN', nombre: 'Almacén', requiereAforo: false },
    { codigo: 'TALLER', nombre: 'Taller', requiereAforo: true },
    { codigo: 'COMEDOR', nombre: 'Comedor', requiereAforo: true },
    { codigo: 'COCINA', nombre: 'Cocina', requiereAforo: false },
    { codigo: 'AUDITORIO', nombre: 'Auditorio', requiereAforo: true },
    { codigo: 'OTRO', nombre: 'Otro', requiereAforo: false },
  ],
} as const;
