export const catalogos = {
  estadosConservacion: [
    { codigo: 'NUEVO', nombre: 'Nuevo', orden: 1, activo: true },
    { codigo: 'BUENO', nombre: 'Bueno', orden: 2, activo: true },
    { codigo: 'REGULAR', nombre: 'Regular', orden: 3, activo: true },
    { codigo: 'MALO', nombre: 'Malo', orden: 4, activo: true },
    { codigo: 'CRITICO', nombre: 'Crítico', orden: 5, activo: true },
    { codigo: 'NO_EVALUADO', nombre: 'No evaluado', orden: 6, activo: true },
  ],
  tiposComponenteInfraestructura: [
    {
      codigo: 'PUERTA',
      nombre: 'Puerta',
      categoria: 'ARQUITECTONICO',
      activo: true,
    },
    {
      codigo: 'VENTANA',
      nombre: 'Ventana',
      categoria: 'ARQUITECTONICO',
      activo: true,
    },
    { codigo: 'MURO', nombre: 'Muro', categoria: 'ESTRUCTURAL', activo: true },
    {
      codigo: 'COLUMNA',
      nombre: 'Columna',
      categoria: 'ESTRUCTURAL',
      activo: true,
    },
    {
      codigo: 'TECHO',
      nombre: 'Techo',
      categoria: 'ARQUITECTONICO',
      activo: true,
    },
    {
      codigo: 'PISO',
      nombre: 'Piso',
      categoria: 'ARQUITECTONICO',
      activo: true,
    },
    {
      codigo: 'ESCALERA',
      nombre: 'Escalera',
      categoria: 'ARQUITECTONICO',
      activo: true,
    },
    {
      codigo: 'RAMPA',
      nombre: 'Rampa',
      categoria: 'ACCESIBILIDAD',
      activo: true,
    },
    {
      codigo: 'ASCENSOR',
      nombre: 'Ascensor',
      categoria: 'ACCESIBILIDAD',
      activo: true,
    },
    {
      codigo: 'LUMINARIA',
      nombre: 'Luminaria',
      categoria: 'ELECTRICO',
      activo: true,
    },
    {
      codigo: 'TOMACORRIENTE',
      nombre: 'Tomacorriente',
      categoria: 'ELECTRICO',
      activo: true,
    },
    {
      codigo: 'TABLERO_ELECTRICO',
      nombre: 'Tablero eléctrico',
      categoria: 'ELECTRICO',
      activo: true,
    },
    {
      codigo: 'LAVATORIO',
      nombre: 'Lavatorio',
      categoria: 'SANITARIO',
      activo: true,
    },
    {
      codigo: 'INODORO',
      nombre: 'Inodoro',
      categoria: 'SANITARIO',
      activo: true,
    },
    { codigo: 'CERCO', nombre: 'Cerco', categoria: 'SEGURIDAD', activo: true },
    {
      codigo: 'PORTON',
      nombre: 'Portón',
      categoria: 'SEGURIDAD',
      activo: true,
    },
    { codigo: 'OTRO', nombre: 'Otro', categoria: 'OTRO', activo: true },
  ],
  unidadesMedida: [
    {
      codigo: 'UNIDAD',
      nombre: 'Unidad',
      simbolo: 'ud',
      magnitud: 'CANTIDAD',
      activo: true,
    },
    {
      codigo: 'METRO',
      nombre: 'Metro',
      simbolo: 'm',
      magnitud: 'LONGITUD',
      activo: true,
    },
    {
      codigo: 'METRO_CUADRADO',
      nombre: 'Metro cuadrado',
      simbolo: 'm²',
      magnitud: 'SUPERFICIE',
      activo: true,
    },
    {
      codigo: 'METRO_CUBICO',
      nombre: 'Metro cúbico',
      simbolo: 'm³',
      magnitud: 'VOLUMEN',
      activo: true,
    },
    {
      codigo: 'LITRO',
      nombre: 'Litro',
      simbolo: 'L',
      magnitud: 'VOLUMEN',
      activo: true,
    },
    {
      codigo: 'KILOGRAMO',
      nombre: 'Kilogramo',
      simbolo: 'kg',
      magnitud: 'MASA',
      activo: true,
    },
  ],
  tiposEspacioFisico: [
    {
      codigo: 'AULA',
      nombre: 'Aula',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'LABORATORIO',
      nombre: 'Laboratorio',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'BIBLIOTECA',
      nombre: 'Biblioteca',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'OFICINA',
      nombre: 'Oficina',
      descripcion: null,
      activo: true,
      requiere_aforo: false,
    },
    {
      codigo: 'SALA_REUNIONES',
      nombre: 'Sala de reuniones',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'SERVICIOS_HIGIENICOS',
      nombre: 'Servicios higiénicos',
      descripcion: null,
      activo: true,
      requiere_aforo: false,
    },
    {
      codigo: 'ALMACEN',
      nombre: 'Almacén',
      descripcion: null,
      activo: true,
      requiere_aforo: false,
    },
    {
      codigo: 'TALLER',
      nombre: 'Taller',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'COMEDOR',
      nombre: 'Comedor',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'COCINA',
      nombre: 'Cocina',
      descripcion: null,
      activo: true,
      requiere_aforo: false,
    },
    {
      codigo: 'AUDITORIO',
      nombre: 'Auditorio',
      descripcion: null,
      activo: true,
      requiere_aforo: true,
    },
    {
      codigo: 'OTRO',
      nombre: 'Otro',
      descripcion: null,
      activo: true,
      requiere_aforo: false,
    },
  ],
} as const;
