export const catalogos = {
  tiposServicioBasico: [
    'AGUA_POTABLE',
    'ENERGIA_ELECTRICA',
    'ALCANTARILLADO',
    'INTERNET',
    'TELEFONIA',
    'GAS',
    'RECOLECCION_RESIDUOS',
  ],
  tiposElementoInfraestructura: [
    'PREDIO',
    'EDIFICACION',
    'NIVEL',
    'ESPACIO_FISICO',
    'ESPACIO_EXTERIOR',
    'COMPONENTE',
  ],
  estadosConservacion: [
    'NUEVO',
    'BUENO',
    'REGULAR',
    'MALO',
    'CRITICO',
    'NO_EVALUADO',
  ],
  tiposTenenciaPredio: ['PROPIO', 'ALQUILADO', 'CEDIDO', 'CONCESION', 'OTRO'],
  tiposEdificacion: [
    'ACADEMICA',
    'ADMINISTRATIVA',
    'DEPORTIVA',
    'SERVICIOS',
    'MIXTA',
    'OTRA',
  ],
  tiposEspacioFisico: [
    'AULA',
    'LABORATORIO',
    'BIBLIOTECA',
    'OFICINA',
    'SALA_REUNIONES',
    'SERVICIOS_HIGIENICOS',
    'ALMACEN',
    'TALLER',
    'COMEDOR',
    'COCINA',
    'AUDITORIO',
    'OTRO',
  ],
  tiposEspacioExterior: [
    'PATIO',
    'LOSA_DEPORTIVA',
    'CANCHA',
    'JARDIN',
    'ESTACIONAMIENTO',
    'AREA_CIRCULACION',
    'OTRO',
  ],
  tiposComponenteInfraestructura: [
    'PUERTA',
    'VENTANA',
    'MURO',
    'COLUMNA',
    'TECHO',
    'PISO',
    'ESCALERA',
    'RAMPA',
    'ASCENSOR',
    'LUMINARIA',
    'TOMACORRIENTE',
    'TABLERO_ELECTRICO',
    'LAVATORIO',
    'INODORO',
    'CERCO',
    'PORTON',
    'OTRO',
  ],
  unidadesMedida: [
    'UNIDAD',
    'METRO',
    'METRO_CUADRADO',
    'METRO_CUBICO',
    'LITRO',
    'KILOGRAMO',
  ],
} as const;
