export const tiposDocumentoIdentidad = [
  {
    codigo: 'DNI',
    nombre: 'Documento Nacional de Identidad',
    longitud_minima: 8,
    longitud_maxima: 8,
    patron: '^[0-9]{8}$',
    activo: true,
  },
  {
    codigo: 'CARNET_EXTRANJERIA',
    nombre: 'Carnet de Extranjería',
    longitud_minima: 9,
    longitud_maxima: 12,
    patron: null,
    activo: true,
  },
  {
    codigo: 'PASAPORTE',
    nombre: 'Pasaporte',
    longitud_minima: 6,
    longitud_maxima: 9,
    patron: null,
    activo: true,
  },
  {
    codigo: 'CPP',
    nombre: 'Cédula de Identidad Personal',
    longitud_minima: 8,
    longitud_maxima: 10,
    patron: null,
    activo: true,
  },
  {
    codigo: 'PARTIDA_NACIMIENTO',
    nombre: 'Partida de Nacimiento',
    longitud_minima: null,
    longitud_maxima: null,
    patron: null,
    activo: true,
  },
  {
    codigo: 'OTRO',
    nombre: 'Otro documento',
    longitud_minima: null,
    longitud_maxima: null,
    patron: null,
    activo: true,
  },
] as const;
