export const permisosSistema = [
  {
    recurso: 'INSTITUCIONES',
    accion: 'LEER',
    codigo: 'INSTITUCIONES.LEER',
    descripcion: 'Ver instituciones educativas',
  },
  {
    recurso: 'INSTITUCIONES',
    accion: 'CREAR',
    codigo: 'INSTITUCIONES.CREAR',
    descripcion: 'Crear instituciones educativas',
  },
  {
    recurso: 'INSTITUCIONES',
    accion: 'ACTUALIZAR',
    codigo: 'INSTITUCIONES.ACTUALIZAR',
    descripcion: 'Actualizar instituciones educativas',
  },
  {
    recurso: 'INSTITUCIONES',
    accion: 'CONSULTAR_RUC',
    codigo: 'INSTITUCIONES.CONSULTAR_RUC',
    descripcion: 'Consultar RUC en APIs externas',
  },
  {
    recurso: 'SEDES',
    accion: 'LEER',
    codigo: 'SEDES.LEER',
    descripcion: 'Ver sedes',
  },
  {
    recurso: 'SEDES',
    accion: 'CREAR',
    codigo: 'SEDES.CREAR',
    descripcion: 'Crear sedes',
  },
  {
    recurso: 'SEDES',
    accion: 'ACTUALIZAR',
    codigo: 'SEDES.ACTUALIZAR',
    descripcion: 'Actualizar sedes',
  },
  {
    recurso: 'INFRAESTRUCTURA',
    accion: 'LEER',
    codigo: 'INFRAESTRUCTURA.LEER',
    descripcion: 'Ver infraestructura física',
  },
  {
    recurso: 'INFRAESTRUCTURA',
    accion: 'GESTIONAR',
    codigo: 'INFRAESTRUCTURA.GESTIONAR',
    descripcion: 'Gestionar infraestructura física',
  },
  {
    recurso: 'USUARIOS',
    accion: 'LEER',
    codigo: 'USUARIOS.LEER',
    descripcion: 'Ver usuarios',
  },
  {
    recurso: 'USUARIOS',
    accion: 'CREAR',
    codigo: 'USUARIOS.CREAR',
    descripcion: 'Crear usuarios',
  },
  {
    recurso: 'USUARIOS',
    accion: 'GESTIONAR_ROLES',
    codigo: 'USUARIOS.GESTIONAR_ROLES',
    descripcion: 'Asignar roles a usuarios',
  },
  {
    recurso: 'PERSONAS',
    accion: 'LEER',
    codigo: 'PERSONAS.LEER',
    descripcion: 'Ver personas',
  },
  {
    recurso: 'PERSONAS',
    accion: 'CREAR',
    codigo: 'PERSONAS.CREAR',
    descripcion: 'Registrar personas',
  },
  {
    recurso: 'PERSONAS',
    accion: 'ACTUALIZAR',
    codigo: 'PERSONAS.ACTUALIZAR',
    descripcion: 'Actualizar personas',
  },
  {
    recurso: 'PERSONAS',
    accion: 'CAMBIAR_ESTADO',
    codigo: 'PERSONAS.CAMBIAR_ESTADO',
    descripcion: 'Cambiar estado de personas',
  },
  {
    recurso: 'PERSONAS',
    accion: 'GESTIONAR_DOCUMENTOS',
    codigo: 'PERSONAS.GESTIONAR_DOCUMENTOS',
    descripcion: 'Gestionar documentos de identidad',
  },
  {
    recurso: 'PERSONAS',
    accion: 'GESTIONAR_CONTACTOS',
    codigo: 'PERSONAS.GESTIONAR_CONTACTOS',
    descripcion: 'Gestionar medios de contacto',
  },
  {
    recurso: 'PERSONAS',
    accion: 'GESTIONAR_DIRECCIONES',
    codigo: 'PERSONAS.GESTIONAR_DIRECCIONES',
    descripcion: 'Gestionar direcciones',
  },
  {
    recurso: 'PERSONAS',
    accion: 'VINCULAR_USUARIO',
    codigo: 'PERSONAS.VINCULAR_USUARIO',
    descripcion: 'Vincular persona a membresía',
  },
  {
    recurso: 'PERSONAS',
    accion: 'CONSULTAR_DNI',
    codigo: 'PERSONAS.CONSULTAR_DNI',
    descripcion: 'Consultar DNI en APIs externas',
  },
  {
    recurso: 'GEOGRAFIA',
    accion: 'CALCULAR_RUTA',
    codigo: 'GEOGRAFIA.CALCULAR_RUTA',
    descripcion: 'Calcular rutas geográficas',
  },
  {
    recurso: 'PANEL_INSTITUCIONAL',
    accion: 'RESUMEN.LEER',
    codigo: 'PANEL_INSTITUCIONAL.RESUMEN.LEER',
    descripcion: 'Ver el resumen del panel institucional',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'LEER',
    codigo: 'ESTUDIANTES.LEER',
    descripcion: 'Ver estudiantes',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'CREAR',
    codigo: 'ESTUDIANTES.CREAR',
    descripcion: 'Crear estudiantes',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'ACTUALIZAR',
    codigo: 'ESTUDIANTES.ACTUALIZAR',
    descripcion: 'Actualizar estudiantes',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'CAMBIAR_ESTADO',
    codigo: 'ESTUDIANTES.CAMBIAR_ESTADO',
    descripcion: 'Cambiar estado de estudiantes',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'APODERADOS.GESTIONAR',
    codigo: 'ESTUDIANTES.APODERADOS.GESTIONAR',
    descripcion: 'Gestionar apoderados de estudiantes',
  },
  {
    recurso: 'ESTUDIANTES',
    accion: 'DOCUMENTOS.GESTIONAR',
    codigo: 'ESTUDIANTES.DOCUMENTOS.GESTIONAR',
    descripcion: 'Gestionar documentos de estudiantes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'LEER',
    codigo: 'DOCENTES.LEER',
    descripcion: 'Ver docentes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'CREAR',
    codigo: 'DOCENTES.CREAR',
    descripcion: 'Registrar docentes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'ACTUALIZAR',
    codigo: 'DOCENTES.ACTUALIZAR',
    descripcion: 'Actualizar datos de docentes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'CAMBIAR_ESTADO',
    codigo: 'DOCENTES.CAMBIAR_ESTADO',
    descripcion: 'Cambiar estado de docentes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'GESTIONAR_SEDES',
    codigo: 'DOCENTES.GESTIONAR_SEDES',
    descripcion: 'Gestionar asignaciones de sede de docentes',
  },
  {
    recurso: 'DOCENTES',
    accion: 'GESTIONAR_ESPECIALIDADES',
    codigo: 'DOCENTES.GESTIONAR_ESPECIALIDADES',
    descripcion: 'Gestionar especialidades profesionales de docentes',
  },
  {
    recurso: 'ESPECIALIDADES_PROFESIONALES',
    accion: 'LEER',
    codigo: 'ESPECIALIDADES_PROFESIONALES.LEER',
    descripcion: 'Ver catálogo de especialidades profesionales',
  },
  {
    recurso: 'ESPECIALIDADES_PROFESIONALES',
    accion: 'CREAR',
    codigo: 'ESPECIALIDADES_PROFESIONALES.CREAR',
    descripcion: 'Crear especialidades profesionales',
  },
  {
    recurso: 'ESPECIALIDADES_PROFESIONALES',
    accion: 'ACTUALIZAR',
    codigo: 'ESPECIALIDADES_PROFESIONALES.ACTUALIZAR',
    descripcion: 'Actualizar especialidades profesionales',
  },
] as const;

export const rolesSistema = [
  {
    codigo: 'PROPIETARIO_PLATAFORMA',
    nombre: 'Propietario de plataforma',
    descripcion: 'Acceso total a la plataforma',
    ambito: 'PLATAFORMA',
  },
  {
    codigo: 'ADMINISTRADOR_INSTITUCION',
    nombre: 'Administrador de institución',
    descripcion: 'Administración completa de una institución educativa',
    ambito: 'INSTITUCION',
  },
  {
    codigo: 'DIRECTOR_SEDE',
    nombre: 'Director de sede',
    descripcion: 'Gestión de una sede educativa',
    ambito: 'SEDE',
  },
  {
    codigo: 'DOCENTE',
    nombre: 'Docente',
    descripcion: 'Acceso al perfil propio del docente',
    ambito: 'SEDE',
  },
] as const;

export const permisosAdministradorInstitucion = [
  'INSTITUCIONES.LEER',
  'INSTITUCIONES.ACTUALIZAR',
  'INSTITUCIONES.CONSULTAR_RUC',
  'SEDES.LEER',
  'SEDES.CREAR',
  'SEDES.ACTUALIZAR',
  'INFRAESTRUCTURA.LEER',
  'INFRAESTRUCTURA.GESTIONAR',
  'USUARIOS.LEER',
  'USUARIOS.CREAR',
  'USUARIOS.GESTIONAR_ROLES',
  'PERSONAS.LEER',
  'PERSONAS.CREAR',
  'PERSONAS.ACTUALIZAR',
  'PERSONAS.CAMBIAR_ESTADO',
  'PERSONAS.GESTIONAR_DOCUMENTOS',
  'PERSONAS.GESTIONAR_CONTACTOS',
  'PERSONAS.GESTIONAR_DIRECCIONES',
  'PERSONAS.VINCULAR_USUARIO',
  'PERSONAS.CONSULTAR_DNI',
  'GEOGRAFIA.CALCULAR_RUTA',
  'PANEL_INSTITUCIONAL.RESUMEN.LEER',
  'ESTUDIANTES.LEER',
  'ESTUDIANTES.CREAR',
  'ESTUDIANTES.ACTUALIZAR',
  'ESTUDIANTES.CAMBIAR_ESTADO',
  'ESTUDIANTES.APODERADOS.GESTIONAR',
  'ESTUDIANTES.DOCUMENTOS.GESTIONAR',
  'DOCENTES.LEER',
  'DOCENTES.CREAR',
  'DOCENTES.ACTUALIZAR',
  'DOCENTES.CAMBIAR_ESTADO',
  'DOCENTES.GESTIONAR_SEDES',
  'DOCENTES.GESTIONAR_ESPECIALIDADES',
  'ESPECIALIDADES_PROFESIONALES.LEER',
  'ESPECIALIDADES_PROFESIONALES.CREAR',
  'ESPECIALIDADES_PROFESIONALES.ACTUALIZAR',
] as const;

export const permisosDirectorSede = [
  'SEDES.LEER',
  'INFRAESTRUCTURA.LEER',
  'PERSONAS.LEER',
  'PERSONAS.CREAR',
  'PERSONAS.ACTUALIZAR',
  'PERSONAS.GESTIONAR_DOCUMENTOS',
  'PERSONAS.GESTIONAR_CONTACTOS',
  'PERSONAS.GESTIONAR_DIRECCIONES',
  'PERSONAS.CONSULTAR_DNI',
  'PANEL_INSTITUCIONAL.RESUMEN.LEER',
  'ESTUDIANTES.LEER',
  'ESTUDIANTES.CREAR',
  'ESTUDIANTES.ACTUALIZAR',
  'ESTUDIANTES.CAMBIAR_ESTADO',
  'ESTUDIANTES.APODERADOS.GESTIONAR',
  'ESTUDIANTES.DOCUMENTOS.GESTIONAR',
  'DOCENTES.LEER',
  'DOCENTES.ACTUALIZAR',
  'DOCENTES.GESTIONAR_SEDES',
  'ESPECIALIDADES_PROFESIONALES.LEER',
] as const;

export const permisosDocente = [
  'DOCENTES.LEER',
  'ESPECIALIDADES_PROFESIONALES.LEER',
  'PANEL_INSTITUCIONAL.RESUMEN.LEER',
] as const;
