export const REPOSITORIO_USUARIOS = Symbol('REPOSITORIO_USUARIOS');
export const REPOSITORIO_MEMBRESIAS = Symbol('REPOSITORIO_MEMBRESIAS');
export const REPOSITORIO_ROLES = Symbol('REPOSITORIO_ROLES');
export const REPOSITORIO_SESIONES = Symbol('REPOSITORIO_SESIONES');
export const REPOSITORIO_INVITACIONES = Symbol('REPOSITORIO_INVITACIONES');
export const REPOSITORIO_AUDITORIA = Symbol('REPOSITORIO_AUDITORIA');
export const REPOSITORIO_CONFIGURACIONES = Symbol(
  'REPOSITORIO_CONFIGURACIONES',
);
